-- items-seed.sql
-- GENERATED by print/scrape/07_generate_seed_sql.py from hawih-catalog.json — do not edit by hand.
-- apply to the HAWIH tenant DB only, AFTER migration 007
--
-- Idempotent: every statement is INSERT ... SELECT ... WHERE NOT EXISTS, safe to re-run.
-- Table prefix: rise_ . Custom fields (print_slug, print_options, name_en,
-- description_en, requires_artwork) must already exist on related_to='items' (migration 007);
-- missing fields are skipped gracefully by the JOIN.

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- Categories -> rise_item_categories
-- ---------------------------------------------------------------------------

INSERT INTO rise_item_categories (title, deleted)
SELECT 'ملصقات', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'ملصقات' AND deleted = 0
);

INSERT INTO rise_item_categories (title, deleted)
SELECT 'كروت الأعمال', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'كروت الأعمال' AND deleted = 0
);

INSERT INTO rise_item_categories (title, deleted)
SELECT 'أوراق رسمية', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'أوراق رسمية' AND deleted = 0
);

INSERT INTO rise_item_categories (title, deleted)
SELECT 'علب وصناديق', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'علب وصناديق' AND deleted = 0
);

INSERT INTO rise_item_categories (title, deleted)
SELECT 'أكياس', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'أكياس' AND deleted = 0
);

INSERT INTO rise_item_categories (title, deleted)
SELECT 'ورق تغليف', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'ورق تغليف' AND deleted = 0
);

INSERT INTO rise_item_categories (title, deleted)
SELECT 'مطبوعات المناسبات', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'مطبوعات المناسبات' AND deleted = 0
);

INSERT INTO rise_item_categories (title, deleted)
SELECT 'أظرف', 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_item_categories WHERE title = 'أظرف' AND deleted = 0
);

-- ---------------------------------------------------------------------------
-- Products -> rise_items (files='a:0:{}' = empty serialized array)
-- ---------------------------------------------------------------------------

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'ملصقات دائرية', 'ملصقات دائرية مقصوصة بدقة تناسب تغليف المنتجات وإغلاق العلب وهوية متجرك. اطبعها بألوان زاهية على خامة لامعة أو مطفية أو شفافة. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 49, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'ملصقات' AND deleted = 0 LIMIT 1),
  0, 1, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'ملصقات دائرية' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'كروت أعمال مطفية', 'كروت أعمال بتشطيب مطفي أنيق يمنح ملمساً راقياً ويقلل الانعكاس. متوفرة بوجه واحد أو وجهين على ورق مقوى 300 أو 350 جرام. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 89, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'كروت الأعمال' AND deleted = 0 LIMIT 1),
  0, 2, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'كروت أعمال مطفية' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'كروت أعمال فاخرة (طبقة مخملية)', 'كروت أعمال بطبقة مخملية ناعمة الملمس تعطي انطباعاً فاخراً لا يُنسى، مع خيار بريق ذهبي للتفاصيل. مثالية للعلامات التي تريد التميّز. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 149, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'كروت الأعمال' AND deleted = 0 LIMIT 1),
  0, 3, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'كروت أعمال فاخرة (طبقة مخملية)' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'ورق مراسلات رسمي', 'أوراق مراسلات رسمية تحمل هوية منشأتك للعقود والخطابات والفواتير. طباعة نظيفة على ورق فاخر بمقاس A4 أو A5. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 120, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'أوراق رسمية' AND deleted = 0 LIMIT 1),
  0, 4, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'ورق مراسلات رسمي' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'علب كرافت مخصصة', 'علب كرافت متينة قابلة للتخصيص تناسب تغليف منتجاتك وطلبات المتاجر الإلكترونية. متوفرة بخامة كرافت طبيعية أو بيضاء مطلية وبعدة مقاسات. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 210, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'علب وصناديق' AND deleted = 0 LIMIT 1),
  0, 5, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'علب كرافت مخصصة' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'أكياس ورقية بمقبض', 'أكياس ورقية أنيقة بمقبض تحمل شعار متجرك وتترك انطباعاً راقياً لدى العملاء. متوفرة بعدة مقاسات وبطباعة لون واحد أو ألوان كاملة. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 180, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'أكياس' AND deleted = 0 LIMIT 1),
  0, 6, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'أكياس ورقية بمقبض' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'ورق تغليف مخصص', 'ورق تغليف مطبوع بنقشتك أو شعارك يضيف لمسة مميزة لهدايا متجرك ومناسباتك. متوفر بمقاسات 50×70 و70×100. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 95, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'ورق تغليف' AND deleted = 0 LIMIT 1),
  0, 7, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'ورق تغليف مخصص' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'دعوات مناسبات', 'دعوات مطبوعة بتصاميم راقية لمناسباتك من أعراس ومؤتمرات وحفلات. متوفرة على ورق كوشيه أو فاخر وبطباعة وجه واحد أو وجهين. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 130, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'مطبوعات المناسبات' AND deleted = 0 LIMIT 1),
  0, 8, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'دعوات مناسبات' AND deleted = 0
);

INSERT INTO rise_items
  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)
SELECT 'أظرف مطبوعة', 'أظرف مطبوعة بهوية منشأتك للمراسلات الرسمية والدعوات. متوفرة بمقاس DL أو A5 وبطباعة لون واحد أو ألوان كاملة. التنفيذ 3-7 أيام عمل والتوصيل 2-5 أيام.', 'الطلب', 75, 'a:0:{}', 1,
  (SELECT id FROM rise_item_categories WHERE title = 'أظرف' AND deleted = 0 LIMIT 1),
  0, 9, 0
WHERE NOT EXISTS (
  SELECT 1 FROM rise_items WHERE title = 'أظرف مطبوعة' AND deleted = 0
);

-- ---------------------------------------------------------------------------
-- Custom field values -> rise_custom_field_values (related_to_type='items')
-- Matched to rise_custom_fields by title WHERE related_to='items'.
-- ---------------------------------------------------------------------------

-- print_slug :: ملصقات دائرية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'round-stickers', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ملصقات دائرية' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: ملصقات دائرية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"المقاس","name_en":"Size","type":"select","values":[{"label_ar":"4 سم","label_en":"4 cm"},{"label_ar":"6 سم","label_en":"6 cm"},{"label_ar":"8 سم","label_en":"8 cm"}]},{"name_ar":"الخامة","name_en":"Material","type":"select","values":[{"label_ar":"لامع","label_en":"Glossy"},{"label_ar":"مطفي","label_en":"Matte"},{"label_ar":"شفاف","label_en":"Clear"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"100","price_delta":0},{"label":"250","price_delta":35},{"label":"500","price_delta":80}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ملصقات دائرية' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: ملصقات دائرية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Round Stickers', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ملصقات دائرية' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: ملصقات دائرية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Precision die-cut round stickers ideal for product packaging, box seals, and brand touches. Vivid print on glossy, matte, or clear stock. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ملصقات دائرية' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: ملصقات دائرية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ملصقات دائرية' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: كروت أعمال مطفية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'matte-business-cards', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال مطفية' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: كروت أعمال مطفية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"الطباعة","name_en":"Printing","type":"select","values":[{"label_ar":"وجه واحد","label_en":"Single-sided"},{"label_ar":"وجهين","label_en":"Double-sided"}]},{"name_ar":"الخامة","name_en":"Material","type":"select","values":[{"label_ar":"300 جم","label_en":"300gsm"},{"label_ar":"350 جم فاخر","label_en":"350gsm Premium"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"100","price_delta":0},{"label":"250","price_delta":40},{"label":"500","price_delta":90}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال مطفية' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: كروت أعمال مطفية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Matte Business Cards', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال مطفية' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: كروت أعمال مطفية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Business cards with an elegant matte finish that feels premium and cuts glare. Single- or double-sided on 300gsm or luxe 350gsm stock. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال مطفية' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: كروت أعمال مطفية
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال مطفية' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: كروت أعمال فاخرة (طبقة مخملية)
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'velvet-business-cards', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال فاخرة (طبقة مخملية)' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: كروت أعمال فاخرة (طبقة مخملية)
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"الطباعة","name_en":"Printing","type":"select","values":[{"label_ar":"وجه واحد","label_en":"Single-sided"},{"label_ar":"وجهين","label_en":"Double-sided"}]},{"name_ar":"التشطيب","name_en":"Finish","type":"select","values":[{"label_ar":"مخملي","label_en":"Velvet"},{"label_ar":"بريق ذهبي","label_en":"Gold Foil"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"100","price_delta":0},{"label":"250","price_delta":60}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال فاخرة (طبقة مخملية)' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: كروت أعمال فاخرة (طبقة مخملية)
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Velvet Business Cards', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال فاخرة (طبقة مخملية)' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: كروت أعمال فاخرة (طبقة مخملية)
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Business cards wrapped in a soft velvet-touch laminate for an unforgettable premium feel, with an optional gold foil accent. Perfect for brands that want to stand out. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال فاخرة (طبقة مخملية)' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: كروت أعمال فاخرة (طبقة مخملية)
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'كروت أعمال فاخرة (طبقة مخملية)' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: ورق مراسلات رسمي
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'letterhead-a4', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق مراسلات رسمي' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: ورق مراسلات رسمي
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"المقاس","name_en":"Size","type":"select","values":[{"label_ar":"A4","label_en":"A4"},{"label_ar":"A5","label_en":"A5"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"100","price_delta":0},{"label":"250","price_delta":55},{"label":"500","price_delta":110}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق مراسلات رسمي' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: ورق مراسلات رسمي
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Letterhead Paper', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق مراسلات رسمي' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: ورق مراسلات رسمي
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Official letterhead carrying your brand identity for contracts, letters, and invoices. Clean print on premium stock in A4 or A5. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق مراسلات رسمي' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: ورق مراسلات رسمي
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق مراسلات رسمي' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: علب كرافت مخصصة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'kraft-boxes', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'علب كرافت مخصصة' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: علب كرافت مخصصة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"المقاس","name_en":"Size","type":"select","values":[{"label_ar":"صغير","label_en":"Small"},{"label_ar":"وسط","label_en":"Medium"},{"label_ar":"كبير","label_en":"Large"}]},{"name_ar":"الخامة","name_en":"Material","type":"select","values":[{"label_ar":"كرافت","label_en":"Kraft"},{"label_ar":"أبيض مطلي","label_en":"Coated White"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"50","price_delta":0},{"label":"100","price_delta":90}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'علب كرافت مخصصة' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: علب كرافت مخصصة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Custom Kraft Boxes', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'علب كرافت مخصصة' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: علب كرافت مخصصة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Sturdy customizable kraft boxes for product packaging and e-commerce orders. Choose natural kraft or coated white in several sizes. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'علب كرافت مخصصة' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: علب كرافت مخصصة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'علب كرافت مخصصة' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: أكياس ورقية بمقبض
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'paper-bags', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أكياس ورقية بمقبض' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: أكياس ورقية بمقبض
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"المقاس","name_en":"Size","type":"select","values":[{"label_ar":"صغير","label_en":"Small"},{"label_ar":"وسط","label_en":"Medium"},{"label_ar":"كبير","label_en":"Large"}]},{"name_ar":"الطباعة","name_en":"Printing","type":"select","values":[{"label_ar":"لون واحد","label_en":"One Color"},{"label_ar":"ألوان كاملة","label_en":"Full Color"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"100","price_delta":0},{"label":"250","price_delta":120}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أكياس ورقية بمقبض' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: أكياس ورقية بمقبض
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Handled Paper Bags', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أكياس ورقية بمقبض' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: أكياس ورقية بمقبض
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Elegant handled paper bags carrying your store logo for a premium customer impression. Available in several sizes with one-color or full-color printing. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أكياس ورقية بمقبض' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: أكياس ورقية بمقبض
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أكياس ورقية بمقبض' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: ورق تغليف مخصص
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'wrapping-paper', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق تغليف مخصص' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: ورق تغليف مخصص
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"المقاس","name_en":"Size","type":"select","values":[{"label_ar":"50×70","label_en":"50×70"},{"label_ar":"70×100","label_en":"70×100"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"50","price_delta":0},{"label":"100","price_delta":70}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق تغليف مخصص' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: ورق تغليف مخصص
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Custom Wrapping Paper', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق تغليف مخصص' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: ورق تغليف مخصص
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Custom-printed wrapping paper with your pattern or logo to elevate store gifts and events. Available in 50×70 and 70×100 sheets. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق تغليف مخصص' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: ورق تغليف مخصص
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'ورق تغليف مخصص' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: دعوات مناسبات
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'event-invitations', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'دعوات مناسبات' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: دعوات مناسبات
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"الخامة","name_en":"Material","type":"select","values":[{"label_ar":"كوشيه","label_en":"Coated"},{"label_ar":"فاخر","label_en":"Premium"}]},{"name_ar":"الطباعة","name_en":"Printing","type":"select","values":[{"label_ar":"وجه واحد","label_en":"Single-sided"},{"label_ar":"وجهين","label_en":"Double-sided"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"50","price_delta":0},{"label":"100","price_delta":70}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'دعوات مناسبات' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: دعوات مناسبات
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Event Invitations', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'دعوات مناسبات' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: دعوات مناسبات
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Elegantly printed invitations for weddings, conferences, and celebrations. Available on coated or premium stock, single- or double-sided. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'دعوات مناسبات' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: دعوات مناسبات
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'دعوات مناسبات' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_slug :: أظرف مطبوعة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'printed-envelopes', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أظرف مطبوعة' AND it.deleted = 0
WHERE cf.title = 'print_slug' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- print_options :: أظرف مطبوعة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '[{"name_ar":"المقاس","name_en":"Size","type":"select","values":[{"label_ar":"DL","label_en":"DL"},{"label_ar":"A5","label_en":"A5"}]},{"name_ar":"الطباعة","name_en":"Printing","type":"select","values":[{"label_ar":"لون واحد","label_en":"One Color"},{"label_ar":"ألوان كاملة","label_en":"Full Color"}]},{"name_ar":"الكمية","name_en":"Quantity","type":"tier","values":[{"label":"100","price_delta":0},{"label":"250","price_delta":45}]}]', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أظرف مطبوعة' AND it.deleted = 0
WHERE cf.title = 'print_options' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- name_en :: أظرف مطبوعة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Printed Envelopes', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أظرف مطبوعة' AND it.deleted = 0
WHERE cf.title = 'name_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- description_en :: أظرف مطبوعة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, 'Envelopes printed with your brand identity for official correspondence and invitations. Available in DL or A5 with one-color or full-color printing. Production in 3-7 business days, delivery in 2-5 days.', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أظرف مطبوعة' AND it.deleted = 0
WHERE cf.title = 'description_en' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

-- requires_artwork :: أظرف مطبوعة
INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, deleted)
SELECT cf.id, 'items', it.id, '1', 0
FROM rise_custom_fields cf
JOIN rise_items it ON it.title = 'أظرف مطبوعة' AND it.deleted = 0
WHERE cf.title = 'requires_artwork' AND cf.related_to = 'items'
  AND NOT EXISTS (
    SELECT 1 FROM rise_custom_field_values v
    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'
      AND v.related_to_id = it.id AND v.deleted = 0
  );

