#!/usr/bin/env python3
"""
07_generate_seed_sql.py

Reads the canonical import-contract dataset (hawih-catalog.json) and emits an
idempotent SQL seed (items-seed.sql) for the HAWIH tenant.

The generated SQL uses INSERT ... SELECT ... WHERE NOT EXISTS so it can be
applied repeatedly without creating duplicates. It seeds:
  - rise_item_categories (the 8 print categories)
  - rise_items           (the 9 demo products)
  - rise_custom_field_values for the print custom fields:
        print_slug, print_options (JSON), name_en, description_en, requires_artwork

Custom fields are matched by title on rise_custom_fields WHERE related_to='items'
(created by migration 007). If a field is absent, its value rows are simply skipped
by the JOIN — the products still import.

Usage:
    python3 07_generate_seed_sql.py
Writes: ../reference/seed/items-seed.sql
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
CATALOG = os.path.join(HERE, "..", "reference", "seed", "hawih-catalog.json")
OUT = os.path.join(HERE, "..", "reference", "seed", "items-seed.sql")

HEADER = """-- items-seed.sql
-- GENERATED by print/scrape/07_generate_seed_sql.py from hawih-catalog.json — do not edit by hand.
-- apply to the HAWIH tenant DB only, AFTER migration 007
--
-- Idempotent: every statement is INSERT ... SELECT ... WHERE NOT EXISTS, safe to re-run.
-- Table prefix: rise_ . Custom fields (print_slug, print_options, name_en,
-- description_en, requires_artwork) must already exist on related_to='items' (migration 007);
-- missing fields are skipped gracefully by the JOIN.

SET NAMES utf8mb4;

"""


def q(s):
    """SQL-escape a string literal body (single quotes doubled)."""
    return str(s).replace("'", "''")


def main():
    with open(CATALOG, "r", encoding="utf-8") as fh:
        data = json.load(fh)

    categories = data["categories"]
    items = data["items"]
    cat_name_by_slug = {c["slug"]: c["name_ar"] for c in categories}

    out = [HEADER]

    # ---- Categories ----
    out.append("-- ---------------------------------------------------------------------------\n")
    out.append("-- Categories -> rise_item_categories\n")
    out.append("-- ---------------------------------------------------------------------------\n\n")
    for c in categories:
        title = q(c["name_ar"])
        out.append(
            "INSERT INTO rise_item_categories (title, deleted)\n"
            f"SELECT '{title}', 0\n"
            "WHERE NOT EXISTS (\n"
            f"  SELECT 1 FROM rise_item_categories WHERE title = '{title}' AND deleted = 0\n"
            ");\n\n"
        )

    # ---- Items ----
    out.append("-- ---------------------------------------------------------------------------\n")
    out.append("-- Products -> rise_items (files='a:0:{}' = empty serialized array)\n")
    out.append("-- ---------------------------------------------------------------------------\n\n")
    for sort, it in enumerate(items, start=1):
        title = q(it["title_ar"])
        desc = q(it["description_ar"])
        unit = q(it["unit_type_ar"])
        rate = it["rate"]
        cat_title = q(cat_name_by_slug[it["category_slug"]])
        out.append(
            "INSERT INTO rise_items\n"
            "  (title, description, unit_type, rate, files, show_in_client_portal, category_id, taxable, sort, deleted)\n"
            f"SELECT '{title}', '{desc}', '{unit}', {rate}, 'a:0:{{}}', 1,\n"
            f"  (SELECT id FROM rise_item_categories WHERE title = '{cat_title}' AND deleted = 0 LIMIT 1),\n"
            f"  0, {sort}, 0\n"
            "WHERE NOT EXISTS (\n"
            f"  SELECT 1 FROM rise_items WHERE title = '{title}' AND deleted = 0\n"
            ");\n\n"
        )

    # ---- Custom field values ----
    out.append("-- ---------------------------------------------------------------------------\n")
    out.append("-- Custom field values -> rise_custom_field_values (related_to_type='items')\n")
    out.append("-- Matched to rise_custom_fields by title WHERE related_to='items'.\n")
    out.append("-- ---------------------------------------------------------------------------\n\n")

    def cfv(field_title, item_title_ar, value):
        ft = q(field_title)
        it_t = q(item_title_ar)
        val = q(value)
        return (
            f"-- {field_title} :: {item_title_ar}\n"
            "INSERT INTO rise_custom_field_values (custom_field_id, related_to_type, related_to_id, value, created_at, deleted)\n"
            f"SELECT cf.id, 'items', it.id, '{val}', NOW(), 0\n"
            "FROM rise_custom_fields cf\n"
            f"JOIN rise_items it ON it.title = '{it_t}' AND it.deleted = 0\n"
            f"WHERE cf.title = '{ft}' AND cf.related_to = 'items'\n"
            "  AND NOT EXISTS (\n"
            "    SELECT 1 FROM rise_custom_field_values v\n"
            "    WHERE v.custom_field_id = cf.id AND v.related_to_type = 'items'\n"
            "      AND v.related_to_id = it.id AND v.deleted = 0\n"
            "  );\n\n"
        )

    for it in items:
        title_ar = it["title_ar"]
        options_json = json.dumps(it["options"], ensure_ascii=False, separators=(",", ":"))
        out.append(cfv("print_slug", title_ar, it["slug"]))
        out.append(cfv("print_options", title_ar, options_json))
        out.append(cfv("name_en", title_ar, it["name_en"]))
        out.append(cfv("description_en", title_ar, it["description_en"]))
        out.append(cfv("requires_artwork", title_ar, "1" if it["requires_artwork"] else "0"))

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("".join(out))

    print(f"Wrote {os.path.abspath(OUT)}  ({len(categories)} categories, {len(items)} items)")


if __name__ == "__main__":
    main()
